### ISSUE TITLE
Duplicate/copy selected tasklists?

### ISSUE THREAD

**Issue by krishnoid** [Google-Tasks-Backup/tasks-backup#22]
Sometimes, I'd like to copy a tasklist -- e.g., a completed list from say, last year or a template.  It would be very handy if there was an option/workflow to export/import single/multiple tasklists similarly to the way one can export/import one's entire google task list, to simulate copying one or more task lists.

If an entire workflow like this couldn't be implemented, other options:
* export specific tasklists by name
* extract single/multiple tasklists from a gtbak file, maybe via command-line utility
* select single/multiple tasklists for reimport by name from the import page

would be just as helpful.

In any event, thanks for a great pair of services.

**Comment by Google-Tasks-Backup** [comment]
This would add a LOT of complexity to GTB, and is not directly related to GTB's primary focus, which is to allow a user to backup their tasks.

As a possible workaround, you could export using the "Import/Export CSV" format, then use a spreadsheet application to select/manipulate the exported data, before re-importing with GTI.
