### ISSUE TITLE
forbidden access

### ISSUE THREAD

**Issue by fleapower** [Google-Tasks-Backup/tasks-backup#23]
I have no access to Google Tasks this morning with either my Android App (Tasks), Windows 10 app (gTasks HD Pro), or backing up using the Google-Tasks-Backup.  I get "forbidden" errors.  Specifically, through Google-Tasks-Backup, I get

**HttpError 403 when requesting https://www.googleapis.com/tasks/v1/users/@me/lists?alt=json returned "Forbidden"**

I'm guessing Google changed something since none of my apps work.  The only way I can see my tasks is to use Tasks in Calendar or the Google Tasks Canvas.  Any help?

Thanks.

**Comment by Google-Tasks-Backup** [comment]
I'm closing this, as this is not a GTB issue
